#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.1.240821.1+077322fa26
//       
//       Command:
//           LottieGen -Language Cppwinrt -WinUIVersion 3.0 -InputFile robotGoAnim.json
//       
//       Input file:
//           robotGoAnim.json (898151 bytes created 10:09+09:00 May 11 2025)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "AnimatedVisuals.RobotGoAnim.g.h"

namespace winrt::AnimatedVisuals
{
    // Name:        Comp 1
    // Frame rate:  100 fps
    // Frame count: 3002
    // Duration:    30020.0 mS
    namespace implementation
    {
        class RobotGoAnim
            : public RobotGoAnimT<RobotGoAnim>
        {
            const int c_loadedImageSurfaceCount = 11;
            int m_loadCompletedEventCount{};
            bool m_isImageLoadingAsynchronous{};
            bool m_isImageLoadingCompleted{};
            bool m_isImageLoadingStarted{};
            bool m_isTryCreateAnimatedVisualCalled{};
            winrt::event<Windows::Foundation::TypedEventHandler<
                Microsoft::UI::Xaml::Controls::IDynamicAnimatedVisualSource,
                Windows::Foundation::IInspectable>> m_IDynamicAnimatedVisualSourceEvent{};
            winrt::event<Microsoft::UI::Xaml::Data::PropertyChangedEventHandler> m_PropertyChanged{};
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_1{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_2{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_4{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_5{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_6{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_7{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_8{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_14{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_35{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_36{ nullptr };
            winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface _image_37{ nullptr };
            void EnsureImageLoadingStarted();
            void HandleLoadCompleted(
                winrt::Microsoft::UI::Xaml::Media::LoadedImageSurface sender,
                winrt::Microsoft::UI::Xaml::Media::LoadedImageSourceLoadCompletedEventArgs e);
        public:
            // Animation duration: 30.020 seconds.
            static constexpr int64_t c_durationTicks{ 300200000L };

            winrt::event_token PropertyChanged(winrt::Microsoft::UI::Xaml::Data::PropertyChangedEventHandler const& handler);
            void PropertyChanged(winrt::event_token const& token) noexcept;

            winrt::event_token AnimatedVisualInvalidated(
                winrt::Windows::Foundation::TypedEventHandler<Microsoft::UI::Xaml::Controls::IDynamicAnimatedVisualSource, IInspectable> const& handler);
            void AnimatedVisualInvalidated(winrt::event_token const& token) noexcept;

            /// <summary>
            /// If this property is set to true, <see cref="TryCreateAnimatedVisual"/> will return
            /// null until all images have loaded. When all images have loaded,
            /// <see cref="TryCreateAnimatedVisual"/> will return the AnimatedVisual. Once
            /// <see cref="TryCreateAnimatedVisual"/> is called, changes made to this property will
            /// be ignored. Default value is false.
            /// </summary>
            bool IsImageLoadingAsynchronous();
            void IsImageLoadingAsynchronous(bool value);

            /// <summary>
            /// Returns true if all images have finished loading.
            /// </summary>
            bool IsImageLoadingCompleted();

            winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
                winrt::Microsoft::UI::Composition::Compositor const& compositor);

            winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
                winrt::Microsoft::UI::Composition::Compositor const& compositor,
                winrt::Windows::Foundation::IInspectable& diagnostics);

            // Gets the number of frames in the animation.
            double FrameCount();

            // Gets the framerate of the animation.
            double Framerate();

            // Gets the duration of the animation.
            winrt::Windows::Foundation::TimeSpan Duration();

            // Converts a zero-based frame number to the corresponding progress value denoting the
            // start of the frame.
            double FrameToProgress(double frameNumber);

            // Returns a map from marker names to corresponding progress values.
            winrt::Windows::Foundation::Collections::IMapView<hstring, double> Markers();

            // Sets the color property with the given name, or does nothing if no such property
            // exists.
            void SetColorProperty(hstring const& propertyName, winrt::Windows::UI::Color value);

            // Sets the scalar property with the given name, or does nothing if no such property
            // exists.
            void SetScalarProperty(hstring const& propertyName, double value);
        };
    }

    namespace factory_implementation
    {
        struct RobotGoAnim : RobotGoAnimT<RobotGoAnim, implementation::RobotGoAnim>
        {
        };
    }
}
